export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const ADD_TO_WISH_LIST = "ADD_TO_WISH_LIST";
export const DELETE_WISH_ITEM = "DELETE_WISH_ITEM";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const FETCH_WISH_LIST = "FETCH_WISH_LIST";


