export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const ADD_TO_WISH_LIST = "ADD_TO_WISH_LIST";
export const DELETE_WISH_ITEM = "DELETE_WISH_ITEM";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const FETCH_WISH_LIST = "FETCH_WISH_LIST";
export const REMOVE_USER = "REMOVE_USER";
export const SEE_PRODUCT_DETAIL = "SEE_PRODUCT_DETAIL";
export const FETCH_KEY_SEARCH="FETCH_KEY_SEARCH";
export const FETCH_PRODUCT_DETAIL="FETCH_PRODUCT_DETAIL";
export const ADD_TO_ORDERS = "ADD_TO_ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";




